services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    
    volumes:
      - ./nginx:/etc/nginx/templates
    networks:
      nodenet:
        aliases:
          - admintemplate.test

  admintemplate:
    container_name: admintemplate
    image: node:14
    networks:
      - nodenet
    working_dir: /app
    ports:
      - 4000:4000
    volumes: 
      - .:/app
    command: bash -c "yarn; yarn dev"

networks:
  nodenet:
    driver: bridge
